### ISSUE TITLE
【HelloWorld示例失败】example/simpleapp中示例

### ISSUE THREAD

**Issue by obe007** [Tudongye/m3game#1]
根据README的第一个example/simpleapp示例测试到
DEMO步骤：Step5 编译运行 (我在Windows中测试的)
go build .
./main -idstr example.world1.simple.1 -conf ../../config/simpleapp.toml

最后运行失败，报错为：[ERROR] [runtime/runtime.go:154 Run] InitPlugins err 603-PluginsSetupFail: Factory broker_nats: 5003-NatsSetupFail: Nats.Conntect 127.0.0.1:4222: dial tcp 127.0.0.1:4222: i/o timeout

![image](https://user-images.githubusercontent.com/16457340/229825912-742b1658-709b-429a-bcc5-51f105ec3d54.png)

nats.Connect(cfg.URL) 还需要连接一个127.0.0.1:4222的broker_nats服务，能否在D示例中帮忙贴出这个服务的启动方式，谢谢！

**Comment by Tudongye** [comment]
nats,https://github.com/nats-io/nats-server 是一个高性能消息分发系统，相比较grpc原生的webscoket，nats支持广播和消息缓存，我后面准备用nats重写grpc的传输层。


我现在改了框架代码，最新版本的simple已经不需要nats了（同时也不支持广播）。只需要把consulHost替换为你自己的consul地址就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tudongye/m3game"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 晚上10:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Tudongye/m3game] 【HelloWorld示例失败】example/simpleapp中示例 (Issue #1)





 
根据README的第一个example/simpleapp示例测试到
 DEMO步骤：Step5 编译运行 (我在Windows中测试的)
 go build .
 ./main -idstr example.world1.simple.1 -conf ../../config/simpleapp.toml
 
最后运行失败，报错为：[ERROR] [runtime/runtime.go:154 Run] InitPlugins err 603-PluginsSetupFail: Factory broker_nats: 5003-NatsSetupFail: Nats.Conntect 127.0.0.1:4222: dial tcp 127.0.0.1:4222: i/o timeout
 

 
nats.Connect(cfg.URL) 还需要连接一个127.0.0.1:4222的broker_nats服务，能否在D示例中帮忙贴出这个服务的启动方式，谢谢！
